api_platform:
    # The title of the API.
    title: 'API LAPI'

    # The description of the API.
    description: 'Cette API gère les données de l’application LAPI'

    # The version of the API.
    version: '0.0.1'

    #Necessary to activate client config
    collection:
        pagination:
            client_items_per_page: true # Disabled by default
            items_per_page_parameter_name: itemsPerPage # Default value
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
